#let acronyms = (
  KI: "Künstliche Intelligenz",
  ERP: "Enterprise Resource Planning",
  CRM: "Customer Relationship Management",
  B2B: "Business-to-Business",
  BDC: "SAP Business Data Cloud",
  AE: "Account Executive",
  CLV: "Customer Lifetime Value",
  CX: "Customer Experience",
  SMB: "Small and Medium-Sized Businesses",
  DCA: "Distribution Cost Analysis",
  KAM: "Key Account Management",
  ROI: "Return on Investment",
  SCP: "Strategic Customer Program",
  KMU: "Kleine und Mittelständische Unternehmen",
  SE: "Societas Europaea",
  USP: "Unique Selling Point",
  ECC: "ERP Central Component",
  SaaS: "Software as a Service",
  GEM: "Global Escalation Management",
)