#let acronyms = (
  CBA: "Certificate-Based Authentication",
  FIDO: "Fast Identity Online",
  MFA: "Multi-Factor Authentication",
  OTP: "One-Time Password",
  W3C: "World Wide Web Consortium",
  CTAP: "Client to Authenticator Protocol",
  NIST: "National Institute of Standards and Technology",
  AiTM: "Adversary-in-the-Middle",
  RP: "Relying Party",
  KI: "Künstliche Intelligenz",
  IAG: "Intelligent Authentication Gateway",
  ERP: "Enterprise Resource Planning",
  CRM: "Customer Relationship Management",
  B2B: "Business-to-Business",
  ARR: "Annual Recurring Revenue",
  BDC: "SAP Business Data Cloud",
  BTP: "SAP Business Technology Platform",
  AE: "Account Executive",
  GTM: "Go-to-Market",
  CLV: "Customer Lifetime Value",
  LoB: "Line of Business",
  SaaS: "Software as a Service",
  CX: "Customer Experience",
  SMB: "Small and Medium-Sized Businesses",
  DCA: "Distribution Cost Analysis"
)